// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginUserInfoState = { user_id: string, user_name: string, user_email: string, user_role: string, user_token: string, user_is_logged_in: boolean, };
