[workspace]
members = [
    "platform_core",
    "src-tauri",
    "src-server"
]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

resolver = "2"
