[package]
name = "platform_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[build-dependencies]
ts-rs = "^10.1.0"

[dependencies]
serde.workspace = true
serde_json.workspace = true
ts-rs = "^10.1.0"
chrono = "0.4.40"
